name: CI

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust as needed

      # Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Create virtual environment and install project from pyproject.toml
      - name: Set up virtual environment and install project
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install .

      # Run a basic command to check installation
      - name: Check installation
        run: |
          source env/bin/activate
          template-python

      # Run tests
      - name: Run tests
        run: |
          source env/bin/activate
          pytest .
        env:
          CI: true

      # Code formatting check with black
      - name: Code formatting with black and isort
        run: |
          source env/bin/activate
          pip install black
          pip install isort
          black --check src/
          isort --check src/
